package com.jxau.soft.webchat.po;

import java.util.Date;

public class TbRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.record_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.from_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.to_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.content
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.record_create_time
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private Date recordCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_record.record_status
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    private Integer recordStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.record_id
     *
     * @return the value of tb_record.record_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.record_id
     *
     * @param recordId the value for tb_record.record_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.from_user_id
     *
     * @return the value of tb_record.from_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.from_user_id
     *
     * @param fromUserId the value for tb_record.from_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId == null ? null : fromUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.to_user_id
     *
     * @return the value of tb_record.to_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.to_user_id
     *
     * @param toUserId the value for tb_record.to_user_id
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.content
     *
     * @return the value of tb_record.content
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.content
     *
     * @param content the value for tb_record.content
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.record_create_time
     *
     * @return the value of tb_record.record_create_time
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public Date getRecordCreateTime() {
        return recordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.record_create_time
     *
     * @param recordCreateTime the value for tb_record.record_create_time
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setRecordCreateTime(Date recordCreateTime) {
        this.recordCreateTime = recordCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_record.record_status
     *
     * @return the value of tb_record.record_status
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_record.record_status
     *
     * @param recordStatus the value for tb_record.record_status
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }
}