package com.jxau.soft.webchat.po;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Hanoch
 */
public class TbRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.relation_id
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private String relationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.owner_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private String ownerUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.friend_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private String friendUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.group
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private String group;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.rela_create_time
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private Date relaCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.relation_level
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private Integer relationLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_relation.relation_status
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    private Integer relationStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.relation_id
     *
     * @return the value of tb_relation.relation_id
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public String getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.relation_id
     *
     * @param relationId the value for tb_relation.relation_id
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setRelationId(String relationId) {
        this.relationId = relationId == null ? null : relationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.owner_user
     *
     * @return the value of tb_relation.owner_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public String getOwnerUser() {
        return ownerUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.owner_user
     *
     * @param ownerUser the value for tb_relation.owner_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setOwnerUser(String ownerUser) {
        this.ownerUser = ownerUser == null ? null : ownerUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.friend_user
     *
     * @return the value of tb_relation.friend_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public String getFriendUser() {
        return friendUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.friend_user
     *
     * @param friendUser the value for tb_relation.friend_user
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setFriendUser(String friendUser) {
        this.friendUser = friendUser == null ? null : friendUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.group
     *
     * @return the value of tb_relation.group
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public String getGroup() {
        return group;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.group
     *
     * @param group the value for tb_relation.group
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setGroup(String group) {
        this.group = group == null ? null : group.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.rela_create_time
     *
     * @return the value of tb_relation.rela_create_time
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public Date getRelaCreateTime() {
        return relaCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.rela_create_time
     *
     * @param relaCreateTime the value for tb_relation.rela_create_time
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setRelaCreateTime(Date relaCreateTime) {
        this.relaCreateTime = relaCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.relation_level
     *
     * @return the value of tb_relation.relation_level
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public Integer getRelationLevel() {
        return relationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.relation_level
     *
     * @param relationLevel the value for tb_relation.relation_level
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setRelationLevel(Integer relationLevel) {
        this.relationLevel = relationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_relation.relation_status
     *
     * @return the value of tb_relation.relation_status
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public Integer getRelationStatus() {
        return relationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_relation.relation_status
     *
     * @param relationStatus the value for tb_relation.relation_status
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setRelationStatus(Integer relationStatus) {
        this.relationStatus = relationStatus;
    }

    @Override
    public String toString() {
        return "TbRelation{" +
                "relationId='" + relationId + '\'' +
                ", ownerUser='" + ownerUser + '\'' +
                ", friendUser='" + friendUser + '\'' +
                ", group='" + group + '\'' +
                ", relaCreateTime=" + relaCreateTime +
                ", relationLevel=" + relationLevel +
                ", relationStatus=" + relationStatus +
                '}';
    }
}