package com.jxau.soft.webchat.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TbRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public TbRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRelationIdIsNull() {
            addCriterion("relation_id is null");
            return (Criteria) this;
        }

        public Criteria andRelationIdIsNotNull() {
            addCriterion("relation_id is not null");
            return (Criteria) this;
        }

        public Criteria andRelationIdEqualTo(String value) {
            addCriterion("relation_id =", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotEqualTo(String value) {
            addCriterion("relation_id <>", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThan(String value) {
            addCriterion("relation_id >", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdGreaterThanOrEqualTo(String value) {
            addCriterion("relation_id >=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThan(String value) {
            addCriterion("relation_id <", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLessThanOrEqualTo(String value) {
            addCriterion("relation_id <=", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdLike(String value) {
            addCriterion("relation_id like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotLike(String value) {
            addCriterion("relation_id not like", value, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdIn(List<String> values) {
            addCriterion("relation_id in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotIn(List<String> values) {
            addCriterion("relation_id not in", values, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdBetween(String value1, String value2) {
            addCriterion("relation_id between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andRelationIdNotBetween(String value1, String value2) {
            addCriterion("relation_id not between", value1, value2, "relationId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIsNull() {
            addCriterion("owner_user is null");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIsNotNull() {
            addCriterion("owner_user is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerUserEqualTo(String value) {
            addCriterion("owner_user =", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserNotEqualTo(String value) {
            addCriterion("owner_user <>", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserGreaterThan(String value) {
            addCriterion("owner_user >", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserGreaterThanOrEqualTo(String value) {
            addCriterion("owner_user >=", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserLessThan(String value) {
            addCriterion("owner_user <", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserLessThanOrEqualTo(String value) {
            addCriterion("owner_user <=", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserLike(String value) {
            addCriterion("owner_user like", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserNotLike(String value) {
            addCriterion("owner_user not like", value, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIn(List<String> values) {
            addCriterion("owner_user in", values, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserNotIn(List<String> values) {
            addCriterion("owner_user not in", values, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserBetween(String value1, String value2) {
            addCriterion("owner_user between", value1, value2, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andOwnerUserNotBetween(String value1, String value2) {
            addCriterion("owner_user not between", value1, value2, "ownerUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserIsNull() {
            addCriterion("friend_user is null");
            return (Criteria) this;
        }

        public Criteria andFriendUserIsNotNull() {
            addCriterion("friend_user is not null");
            return (Criteria) this;
        }

        public Criteria andFriendUserEqualTo(String value) {
            addCriterion("friend_user =", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserNotEqualTo(String value) {
            addCriterion("friend_user <>", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserGreaterThan(String value) {
            addCriterion("friend_user >", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserGreaterThanOrEqualTo(String value) {
            addCriterion("friend_user >=", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserLessThan(String value) {
            addCriterion("friend_user <", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserLessThanOrEqualTo(String value) {
            addCriterion("friend_user <=", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserLike(String value) {
            addCriterion("friend_user like", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserNotLike(String value) {
            addCriterion("friend_user not like", value, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserIn(List<String> values) {
            addCriterion("friend_user in", values, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserNotIn(List<String> values) {
            addCriterion("friend_user not in", values, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserBetween(String value1, String value2) {
            addCriterion("friend_user between", value1, value2, "friendUser");
            return (Criteria) this;
        }

        public Criteria andFriendUserNotBetween(String value1, String value2) {
            addCriterion("friend_user not between", value1, value2, "friendUser");
            return (Criteria) this;
        }

        public Criteria andGroupIsNull() {
            addCriterion("group is null");
            return (Criteria) this;
        }

        public Criteria andGroupIsNotNull() {
            addCriterion("group is not null");
            return (Criteria) this;
        }

        public Criteria andGroupEqualTo(String value) {
            addCriterion("group =", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotEqualTo(String value) {
            addCriterion("group <>", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThan(String value) {
            addCriterion("group >", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupGreaterThanOrEqualTo(String value) {
            addCriterion("group >=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThan(String value) {
            addCriterion("group <", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLessThanOrEqualTo(String value) {
            addCriterion("group <=", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupLike(String value) {
            addCriterion("group like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotLike(String value) {
            addCriterion("group not like", value, "group");
            return (Criteria) this;
        }

        public Criteria andGroupIn(List<String> values) {
            addCriterion("group in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotIn(List<String> values) {
            addCriterion("group not in", values, "group");
            return (Criteria) this;
        }

        public Criteria andGroupBetween(String value1, String value2) {
            addCriterion("group between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andGroupNotBetween(String value1, String value2) {
            addCriterion("group not between", value1, value2, "group");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeIsNull() {
            addCriterion("rela_create_time is null");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeIsNotNull() {
            addCriterion("rela_create_time is not null");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeEqualTo(Date value) {
            addCriterion("rela_create_time =", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeNotEqualTo(Date value) {
            addCriterion("rela_create_time <>", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeGreaterThan(Date value) {
            addCriterion("rela_create_time >", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("rela_create_time >=", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeLessThan(Date value) {
            addCriterion("rela_create_time <", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("rela_create_time <=", value, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeIn(List<Date> values) {
            addCriterion("rela_create_time in", values, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeNotIn(List<Date> values) {
            addCriterion("rela_create_time not in", values, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeBetween(Date value1, Date value2) {
            addCriterion("rela_create_time between", value1, value2, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelaCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("rela_create_time not between", value1, value2, "relaCreateTime");
            return (Criteria) this;
        }

        public Criteria andRelationLevelIsNull() {
            addCriterion("relation_level is null");
            return (Criteria) this;
        }

        public Criteria andRelationLevelIsNotNull() {
            addCriterion("relation_level is not null");
            return (Criteria) this;
        }

        public Criteria andRelationLevelEqualTo(Integer value) {
            addCriterion("relation_level =", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelNotEqualTo(Integer value) {
            addCriterion("relation_level <>", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelGreaterThan(Integer value) {
            addCriterion("relation_level >", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("relation_level >=", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelLessThan(Integer value) {
            addCriterion("relation_level <", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelLessThanOrEqualTo(Integer value) {
            addCriterion("relation_level <=", value, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelIn(List<Integer> values) {
            addCriterion("relation_level in", values, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelNotIn(List<Integer> values) {
            addCriterion("relation_level not in", values, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelBetween(Integer value1, Integer value2) {
            addCriterion("relation_level between", value1, value2, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("relation_level not between", value1, value2, "relationLevel");
            return (Criteria) this;
        }

        public Criteria andRelationStatusIsNull() {
            addCriterion("relation_status is null");
            return (Criteria) this;
        }

        public Criteria andRelationStatusIsNotNull() {
            addCriterion("relation_status is not null");
            return (Criteria) this;
        }

        public Criteria andRelationStatusEqualTo(Integer value) {
            addCriterion("relation_status =", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusNotEqualTo(Integer value) {
            addCriterion("relation_status <>", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusGreaterThan(Integer value) {
            addCriterion("relation_status >", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("relation_status >=", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusLessThan(Integer value) {
            addCriterion("relation_status <", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusLessThanOrEqualTo(Integer value) {
            addCriterion("relation_status <=", value, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusIn(List<Integer> values) {
            addCriterion("relation_status in", values, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusNotIn(List<Integer> values) {
            addCriterion("relation_status not in", values, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusBetween(Integer value1, Integer value2) {
            addCriterion("relation_status between", value1, value2, "relationStatus");
            return (Criteria) this;
        }

        public Criteria andRelationStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("relation_status not between", value1, value2, "relationStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_relation
     *
     * @mbg.generated do_not_delete_during_merge Wed May 16 19:54:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}