package com.jxau.soft.webchat.mapper;

import com.jxau.soft.webchat.pojo.TbLog;
import com.jxau.soft.webchat.pojo.TbLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    long countByExample(TbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int deleteByExample(TbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int insert(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int insertSelective(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    List<TbLog> selectByExample(TbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    TbLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbLog record, @Param("example") TbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int updateByExample(@Param("record") TbLog record, @Param("example") TbLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int updateByPrimaryKeySelective(TbLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_log
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    int updateByPrimaryKey(TbLog record);
}