package com.jxau.soft.webchat.mapper;

import com.jxau.soft.webchat.po.TbRecord;
import com.jxau.soft.webchat.po.TbRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    long countByExample(TbRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int deleteByExample(TbRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int insert(TbRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int insertSelective(TbRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    List<TbRecord> selectByExample(TbRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    TbRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbRecord record, @Param("example") TbRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int updateByExample(@Param("record") TbRecord record, @Param("example") TbRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int updateByPrimaryKeySelective(TbRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_record
     *
     * @mbg.generated Thu Apr 19 18:15:38 CST 2018
     */
    int updateByPrimaryKey(TbRecord record);
}