package com.jxau.soft.webchat.mapper;

import com.jxau.soft.webchat.pojo.TbRelation;
import com.jxau.soft.webchat.pojo.TbRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * @author Hanoch
 */
public interface TbRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    long countByExample(TbRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int deleteByExample(TbRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int deleteByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int insert(TbRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int insertSelective(TbRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    List<TbRelation> selectByExample(TbRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    TbRelation selectByPrimaryKey(String relationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TbRelation record, @Param("example") TbRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int updateByExample(@Param("record") TbRelation record, @Param("example") TbRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int updateByPrimaryKeySelective(TbRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_relation
     *
     * @mbg.generated Wed May 16 19:54:29 CST 2018
     */
    int updateByPrimaryKey(TbRelation record);
}