package com.jxau.soft.webchat.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbLog implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.log_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.log_user_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private String logUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.log_create_time
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private Date logCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.log_type
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private String logType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.log_detail
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private String logDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_log.ip
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.log_id
     *
     * @return the value of tb_log.log_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.log_id
     *
     * @param logId the value for tb_log.log_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.log_user_id
     *
     * @return the value of tb_log.log_user_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public String getLogUserId() {
        return logUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.log_user_id
     *
     * @param logUserId the value for tb_log.log_user_id
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setLogUserId(String logUserId) {
        this.logUserId = logUserId == null ? null : logUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.log_create_time
     *
     * @return the value of tb_log.log_create_time
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public Date getLogCreateTime() {
        return logCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.log_create_time
     *
     * @param logCreateTime the value for tb_log.log_create_time
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setLogCreateTime(Date logCreateTime) {
        this.logCreateTime = logCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.log_type
     *
     * @return the value of tb_log.log_type
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public String getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.log_type
     *
     * @param logType the value for tb_log.log_type
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setLogType(String logType) {
        this.logType = logType == null ? null : logType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.log_detail
     *
     * @return the value of tb_log.log_detail
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public String getLogDetail() {
        return logDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.log_detail
     *
     * @param logDetail the value for tb_log.log_detail
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setLogDetail(String logDetail) {
        this.logDetail = logDetail == null ? null : logDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_log.ip
     *
     * @return the value of tb_log.ip
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_log.ip
     *
     * @param ip the value for tb_log.ip
     *
     * @mbg.generated Tue Mar 20 17:14:45 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    @Override
    public String toString() {
        return "TbLog{" +
                "logId='" + logId + '\'' +
                ", logUserId='" + logUserId + '\'' +
                ", logCreateTime=" + logCreateTime +
                ", logType='" + logType + '\'' +
                ", logDetail='" + logDetail + '\'' +
                ", ip='" + ip + '\'' +
                '}';
    }
}