package com.jxau.soft.webchat.pojo;

import java.io.Serializable;
import java.util.Date;

public class TbUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_id
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_nick_name
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private String userNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_sex
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private Integer userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_age
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_profilehead
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private String userProfilehead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_profile
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private String userProfile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_create_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private Date userCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_last_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private Date userLastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.user_status
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    private Integer userStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_id
     *
     * @return the value of tb_user.user_id
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_id
     *
     * @param userId the value for tb_user.user_id
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_nick_name
     *
     * @return the value of tb_user.user_nick_name
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_nick_name
     *
     * @param userNickName the value for tb_user.user_nick_name
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_sex
     *
     * @return the value of tb_user.user_sex
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public Integer getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_sex
     *
     * @param userSex the value for tb_user.user_sex
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserSex(Integer userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_age
     *
     * @return the value of tb_user.user_age
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_age
     *
     * @param userAge the value for tb_user.user_age
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_profilehead
     *
     * @return the value of tb_user.user_profilehead
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public String getUserProfilehead() {
        return userProfilehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_profilehead
     *
     * @param userProfilehead the value for tb_user.user_profilehead
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserProfilehead(String userProfilehead) {
        this.userProfilehead = userProfilehead == null ? null : userProfilehead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_profile
     *
     * @return the value of tb_user.user_profile
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public String getUserProfile() {
        return userProfile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_profile
     *
     * @param userProfile the value for tb_user.user_profile
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserProfile(String userProfile) {
        this.userProfile = userProfile == null ? null : userProfile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_create_time
     *
     * @return the value of tb_user.user_create_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public Date getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_create_time
     *
     * @param userCreateTime the value for tb_user.user_create_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserCreateTime(Date userCreateTime) {
        this.userCreateTime = userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_last_time
     *
     * @return the value of tb_user.user_last_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public Date getUserLastTime() {
        return userLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_last_time
     *
     * @param userLastTime the value for tb_user.user_last_time
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserLastTime(Date userLastTime) {
        this.userLastTime = userLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.user_status
     *
     * @return the value of tb_user.user_status
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.user_status
     *
     * @param userStatus the value for tb_user.user_status
     *
     * @mbg.generated Sun Mar 25 17:06:40 CST 2018
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    @Override
    public String toString() {
        return "TbUser{" +
                "userId='" + userId + '\'' +
                ", password='" + password + '\'' +
                ", userNickName='" + userNickName + '\'' +
                ", userSex=" + userSex +
                ", userAge=" + userAge +
                ", userProfilehead='" + userProfilehead + '\'' +
                ", userProfile='" + userProfile + '\'' +
                ", userCreateTime=" + userCreateTime +
                ", userLastTime=" + userLastTime +
                ", userStatus=" + userStatus +
                '}';
    }
}